### ISSUE TITLE
No differences found

### ISSUE THREAD

**Issue by mslourens** [imgly/rembrandt#9]
I am trying to compare two images (in base64 string format) with the following code:

```javascript
this.images = {
   ref: '<BASE64 STRING>',
   src: '<BASE64 STRING>'
};

async compare() {
    try {
      this.rembrandt = new Rembrandt({
       
        imageA: this.images.ref,
        imageB: this.images.src,
        thresholdType: Rembrandt.THRESHOLD_PERCENT,
        maxThreshold: 0.01,

        // Maximum color delta (0...255):
        maxDelta: 20,

        maxOffset: 0,

        renderComposition: true, 
        compositionMaskColor: Rembrandt.Color.RED 
      });

      this.result = await this.rembrandt.compare();
    } catch (err) {
      console.error(err);
    }
  }
```

When I run this code with rembrandt.js version 0.1.3 (build from the master branch) or installed it via NPM, I get no results (both images are identical, which is not true), but when I try this same code with rembrandt.js code copied from [rembrandt.com](www.rembrandt.com), I get the same results as when I try the example of that same website. Attached are both libraries. Who can spot the difference?

[rembrandt.zip](https://github.com/imgly/rembrandt/files/3133949/rembrandt.zip)

**Comment by keiwando** [comment]
The README here was wrong. The `maxDelta` value needs to be specified as a percentage instead of an 8 bit integer. Thanks for pointing this out!
